### ISSUE TITLE
More easy-to-understand name space configration

### ISSUE THREAD

**Issue by r-yamada1998** [necst-telescope/necst#141]
I hope you are doing well. I am now working on the data reduction programme, and got a little bit inconvenient namespace for the necstdb database.
In the namespace of necst, parameters related to `antenna` is assigned as `necst-OMU1P85M-ctrl-antenna-encoder`, where we can understand this is related to telescope control because of the `ctrl` namespace. The same thing appears in `necst-OMU1P85M-data-spectral-board1`, where `data` is a key identifier. However, the parent namespaces of topic names related to weather loggers are `f"necst-{config.observatory}-"`. For example, temperature and humidity has  `necst-OMU1P85M-humidity` and staff like that namespace. Why don't you change the name space to `necst-OMU1P85M-weather-humidity`?
If you change the name space like `necst-OMU1P85M-weather-humidity`, I can subtract the weather condition data by a
simple code below:
```python
prefix = f"necst-{config.observatory}-"
all_observation_results = [
    tablename for tablename in db.list_tables()
    if tablename.startswith(prefix + "-weather")
]
```

But now, I need to make a list of weather condition parameters before the data loading.

**Comment by KaoruNishikawa** [comment]
@r-yamada1998 
Thank you for the proposal!

The idea will definitely improve the accessibility to *topic groups*.
But there, I think, is another way to realize the improvement; group the data together into single message:

```python
>>> msg = WeatherMsg(humidity=0.5, temperature=279, pressure=855)
```

and publish to the topic named `/necst/{config.observatory}/weather_ambient` or `/necst/{config.observatory}/weather/ambient`.
In my opinion, this is the right place to use newly defined namespace.

I'd like to hear your idea regarding the above-mentioned solution.
