### ISSUE TITLE
Add `"scan"` command to `Commander`

### ISSUE THREAD

**Issue by KaoruNishikawa** [necst-telescope/necst#85]
**What should be realised**

```python
>>> com = Commander()
>>> com.get_privilege()
>>> com.antenna("scan", start=(30, 50), end=(32, 50), speed=150/3600, unit="deg", frame="fk5", wait=True)
```

The above example should perform the following:

1. [blocking if `wait`] Point to $(R.A., Dec.) \simeq (29^\circ, 50^\circ)$ (margin would be read from config file; definition of new parameter is required)
2. [blocking if `wait`] Accelerate in constant rate (`config.max_acceleration` or independently calculated value) to reach the scan `speed` at `start`; $(R.A., Dec.) \simeq (30^\circ, 50^\circ)$
3. [blocking if `wait`] Drive at constant `speed` to `end`; $(R.A., Dec.) \simeq (32^\circ, 50^\circ)$
4. Decelerate and stop in `config.max_acceleration`

**Comment by Kirby1717** [comment]
**Note**
1. _
2. _
3. PathFinder
4. _
